//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::article::Entity as Article;
pub use super::posts::Entity as Posts;
pub use super::user::Entity as User;
pub use super::user_id_create::Entity as UserIdCreate;
